# Having the required CellML files generated by GenerateCellML.py, this script runs the parameter identification.
# To run this script, use the command below (adjusting the path to the script as needed):
# & 'C:\Program Files\OpenCOR\pythonshell.bat' '<path_to_this_script>\RunCalibration.py'
# 
#& 'C:\Program Files\OpenCOR\pythonshell.bat' 'C:\Users\jebollen\OneDrive - UGent\Documents\Research\1-WP\CellModels\0_ABI_SMC\CircAutogen\circulatory_autogen\CA_user\CVS0D\RunCalibration.py'
# 
# But best to run it on multiple cores
# mpiexec -n 12 run_mpi.bat 'C:\Users\jebollen\OneDrive - UGent\Documents\Research\1-WP\CellModels\0_ABI_SMC\CircAutogen\circulatory_autogen\CA_user\CVS0D\RunCalibration.py'


# ===================================================
#                  User setup 
# Define the model specific settings 
# Change the line below as needed to generate the model you want.
#  - model_name
# ===================================================

# Set the model_name 
model_name = "cvs_model_0d"

# ===================================================
#                  Imports and setup 
# Import the necassary libraries and define the dirs
# Nothing needs to be changed.
# ===================================================

from pathlib import Path
import os
import sys
import numpy as np
import pandas as pd
import matplotlib
import datetime

matplotlib.use("Agg")
import matplotlib.pyplot as plt
try:
    import opencor as oc
except:
    print('opencor not available, open this jupyter notebook with a python version that has opencor installed')
    exit()
sys.path.append(str(Path(__file__).resolve().parent.parent.parent / "src"))

print("First imports done")

CA_root = str(Path(__file__).resolve().parent.parent.parent)
src_path = os.path.join(CA_root, "src")
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

CA_user_dir = str(Path(__file__).resolve().parent)
generated_models_dir = os.path.join(CA_user_dir, "generated_models")
param_id_output_dir = os.path.join(CA_user_dir, "param_id_output")
resources_dir = os.path.join(CA_user_dir, "resources") 

print("Paths done")

from utilities.utility_funcs import get_default_inp_data_dict
import pprint
from scripts.script_generate_with_new_architecture import generate_with_new_architecture
from solver_wrappers import get_simulation_helper_from_inp_data_dict
from param_id.paramID import CVS0DParamID
from utilities.obs_data_helpers import ObsDataCreator

print("Second imports done")

# ===================================================
#                  Model dir setup 
# Define the rest of the settings automatically in the input_data_dict
# Nothing needs to be changed. 
# ===================================================

input_param_file = f"{model_name}_parameters.csv"
# Base user inputs (this shows all the settings that can be changed)
inp_data_dict = get_default_inp_data_dict(model_name, input_param_file, resources_dir)
inp_data_dict["generated_models_dir"] = generated_models_dir
inp_data_dict["generated_models_subdir"] = os.path.join(generated_models_dir, model_name)
inp_data_dict["model_path"] = os.path.join(inp_data_dict["generated_models_subdir"], f"{model_name}.cellml")
inp_data_dict["param_id_output_dir"] = param_id_output_dir

print('inp_data_dict set: ')
pprint.pprint(inp_data_dict)


# ===================================================
#       Calibration data & sim. protocol setup
# Set the calibration data to be fitted towards 
# you can fit to timeseries or scalar features
# Adjust the following: pre_time, sim_times, data_dir 
# ===================================================

# Protocol info (this defines your times in SECONDS and changes of inputs in the experiment)
# You can define first a pretime, where the simulation runs without extracting data, and then a sim time, where the data is extracted and fitted towards for different subexperiments. You can also define changes in parameters for each experiment and subexperiment (e.g. to simulate a drug application or a change in extracellular ion concentration).
# In an experiment you define one case, with subexperiments representing a change in a variable in that case
# E.g. for cells: you do a voltage clamp experiment (case) but the cell is first in the organ bath before doing it (pretime) 
# then you apply a fixed voltage step (subexperiment 1) during sim_times[0]. Afterwards you increase the voltage (subexperiment 2) for
# sim_times[1], etc. You can also change parameters for each subexperiment to e.g. simulate a drug application by changing all other parameters

pre_times = [0] #s the pre time for each experiment, how long to run the simulation before extracting the data to be fitted
sim_times =[[5]] #s the simulation time for each subexperiment (run after the pre_time)
obs_dt = 1.0 #s the time step of the data, needed for the parameter identification to simulate for the same time step

# Create dict for the calibration data
obs_data_creator = ObsDataCreator()


# ----------------- 
#     EXAMPLE 1 
# ----------------- 
# Time series fit: you fit the whole time series of a variable to the experimental data. The experimental data should be in a csv file with two columns: 
# time  and the variable you want to fit. You can add as many csv files as you want, just make sure to add them to the obs_data_dict with the correct 
# variable name and units (see below).
# Important: your data needs to be uniformly sampeld in the time domain, i.e. resample to a fixed time interval 

#Where can the calibration data be found
data_dir = r"C:\Users\jebollen\OneDrive - UGent\Documents\Research\1-WP\CellModels\0_ABI_SMC\Data_rats"
gt = np.loadtxt(os.path.join(data_dir, "I_Kv_corrected.csv"), delimiter=",")
time_gt = gt[:,0].flatten()
data_gt = gt[:,1].flatten()

#define the time step of the data, which is needed for the parameter identification as the simulations will simulate for the same timestep
obs_dt = float(time_gt[1] - time_gt[0])

#define the first entry as calibration data, set the correct names
# - variable: the name of the variable corresponding to the calibration data
# - name for plotting: the name that will be used in the plots, you can use LaTeX formatting here (e.g. r"I\_Kv" for I_Kv with an underscore)
# - data type: "series" for time series data, "constant" for scalar features
# - operation: here null because it is a time series fit 
# - operands: what data is extracted from the model to be fitted towards the experimental data, should correspond to the calibration data
# - unit: the unit of the data
# - weight: the weight of this data item in the cost function, can be used to give more importance to certain data items 
# (e.g. if you have a time series and a scalar feature, you might want to give more weight to the scalar feature to ensure the model fits it well)
# value: the value of the calibration data as extraced from the csv file
# std: if you know what the std is per timepoint this can be added here, otherwise you can set it to 1 
# obs_dt: the time step of the data, needed for the parameter identification to simulate for the same time step
# experiment_idx: to what experiment the data corresponds 
# subexperiment_idx: to what subexperiment the data corresponds

entry_time_series = {  
  "variable": "I_Kv",  
  "name_for_plotting": r"I\_Kv",  
  "data_type": "series",  
  "operation": "null",  
  "operands": ["smc_kapela_VoltageClamp/I_Kv"],  
  "unit": "pA",  
  "weight": float(1.0),  
  "value": data_gt.tolist(),  
  "std": np.ones(len(data_gt)).tolist(),  
  "obs_dt": obs_dt,  
  "experiment_idx": 0,  
  "subexperiment_idx": 0  
}

#add the data item to the obs data creator
#obs_data_creator.add_data_item(entry_time_series)

# ----------------- 
#     EXAMPLE 2 
# ----------------- 
# Use a scalar feature to fit towards, e.g. peak or minimum value
# It is the easiest if you just add the value in here instead of loading it via a csv file but could also be possible


#Adapt the following (the ones different from the time series entry are explained below):
# - data type: "constant" for scalar features, "series" for time series data
# - plot_type: 
#      "horizontal" for features that are extracted from the time series and are plotted as a horizontal line in the time series plot, 
#      "vertical" for features that are plotted as a vertical line in the time series plot, 
#       None to not plot this feature
# - operation: there are some build in ones: mean, max, min, max_minus_min, .....
#   custom operations can also be added

entry_scalar = {
    "variable": "u",
    "name_for_plotting": r"u aorta",
    "data_type": "constant",
    "unit": "J_per_m3",
    "value": 13043.0,
    "obs_dt": obs_dt,
    "plot_type": "horizontal",
    "std": 0.0001,
    "operands": ["A_aorta_ascending_1/u"],
    "operation": "max"
}

obs_data_creator.add_data_item(entry_scalar)


# Now also define what parameters need to be changed for each experiment and subexperiment
df = pd.read_csv(os.path.join(resources_dir, "experimental_protocol.csv"))     
params_to_change = {}    
for _, row in df.iterrows():    
    exp_idx = int(row['Experiment'])    
    sub_idx = int(row['subexperiment'])    
    param_name = model_name + "/" + row['variable']    
    value = row['value']    
    if pd.isna(value):    
        continue    
    if param_name not in params_to_change:    
        max_exp = df['Experiment'].max()    
        max_sub = df.groupby('Experiment')['subexperiment'].max().max()    
        params_to_change[param_name] = [[None] * (max_sub + 1) for _ in range(max_exp + 1)]    
    # Convert to native Python type before storing  
    params_to_change[param_name][exp_idx][sub_idx] = float(value) if not pd.isna(value) else None  

print(params_to_change)

obs_data_creator.add_protocol_info(pre_times, sim_times, params_to_change, experiment_labels=["exp0"])  
obs_data_dict = obs_data_creator.get_obs_data_dict()

# ===================================================
#      Read the parameters to do calibration on
# Read from csv the params to change and their range
# change the name of the parameters file
# ===================================================

params_file = os.path.join(resources_dir, f"{model_name}_params_to_change.csv")  

def read_params(filepath):
    all_params = None
    df = pd.read_csv(filepath)
    all_params = df.to_dict(orient="records")
    return all_params

all_params = read_params(params_file)
print(f"Loaded {len(all_params)} parameters")
 
params_for_id_dict = []  

for param in all_params:  
    name = param['variable_name']
    # Create entry with reasonable bounds (you may need to adjust these)  
    entry = {  
        "vessel_name": param["vessel"],  
        "param_name": name,  
        "min": param['min'],
        "max": param['max'],  # Use existing max or default  
        "name_for_plotting": name.replace("_", r"\_")  # Escape underscores for plotting
    }  
    params_for_id_dict.append(entry)  


print(f"Loaded {len(params_for_id_dict)} parameters for calibration")

# ===================================================
#       Calibration solver and process set-up
# Defines the method of identificaiton, wether to run 
# identifiability analysis ... 
# ===================================================

inp_data_dict["param_id_method"] = "genetic_algorithm"
inp_data_dict["DEBUG"] = True

inp_data_dict['do_mcmc'] = False
if (inp_data_dict['do_mcmc']):  
    inp_data_dict['mcmc_options'] = {  
        'num_steps': 1000,  
        'num_walkers': 64,  
        'cost_type': 'MSE',  
        'cost_convergence': 0.001  
    }

param_id = CVS0DParamID.init_from_dict(inp_data_dict)

# Optimiser options (adjust as needed)
optimiser_options = {
    "num_calls_to_function": 100,
    "cost_convergence": 1.0,
    "max_patience": 10,
    "cost_type": "MSE",
}

param_id.set_optimiser_options(optimiser_options)
param_id.set_ground_truth_data(obs_data_dict)
param_id.set_param_id_method(inp_data_dict["param_id_method"])

# now add the params to the param id object
param_id.set_params_for_id(params_for_id_dict)
params_for_id_subset = [ entry for entry in params_for_id_dict]
param_id.set_params_for_id(params_for_id_subset)

# ===================================================
#               Run the calibration 
# ===================================================

# Run calibration
param_id.run()

#Generate new CellML files with updated param values
inp_data_dict["generated_models_subdir"] = os.path.join(generated_models_dir, f"{model_name}_calibrated")
inp_data_dict["param_id_obs_path"] = param_id.param_id_obs_file_prefix
success = generate_with_new_architecture(True, inp_data_dict=inp_data_dict)

# ===================================================
#              Plot the results
# ===================================================

# Shorten file_prefix to avoid Windows MAX_PATH limit
#param_id.file_prefix = f"{model_name}_{datetime.today().strftime('%m%d')}"

# Now do simulate_with_best_param_vals and plotting
param_id.simulate_with_best_param_vals()
param_id.plot_dir = str(param_id_output_dir)
# Ensure plots_param_id subfolder exists under output_dir (used by plot_mcmc chain plot)
os.makedirs(os.path.join(param_id.output_dir, 'plots_param_id'), exist_ok=True)
param_id.plot_outputs()

print("All done!")
sys.stdout.flush()
os._exit(0)  # Clean exit without MPI finalize error